FROM ubuntu:16.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y build-essential
RUN apt-get install gcc valgrind -y
RUN apt-get install gcc -y
RUN apt-get install gsl-bin -y
RUN apt-get install libgsl0-dev -y
